# Generated by Django 3.1.4 on 2020-12-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201222_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='secretary',
            new_name='supervisor',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='supervisor',
            new_name='secretary',
        ),
    ]
