# Generated by Django 3.1.4 on 2020-12-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201223_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.location'),
        ),
    ]
