# Generated by Django 3.1.4 on 2020-12-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='timestamp',
            new_name='created',
        ),
    ]
