# Generated by Django 3.1.4 on 2020-12-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20201221_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
