# Generated by Django 3.1.4 on 2020-12-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20201222_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='deleted_at',
        ),
    ]
