# Generated by Django 3.1.4 on 2020-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Secretary'), (2, 'Supervisor'), (1, 'Admin')]),
        ),
    ]
