# Generated by Django 3.1.4 on 2020-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201220_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Worker'), (3, 'Secretary'), (2, 'Supervisor'), (1, 'Admin')]),
        ),
    ]
