# Generated by Django 3.1.4 on 2020-12-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201220_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('WORKER', 'Worker'), ('SECRETARY', 'Secretary'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')]),
        ),
    ]
