# Generated by Django 3.1.4 on 2020-12-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201222_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('WORKER', 'Worker'), ('SECRETARY', 'Secretary'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')], max_length=50),
        ),
    ]
