# Generated by Django 3.1.4 on 2020-12-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201222_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='deleted_at',
        ),
    ]
